### ISSUE TITLE
Clean up codebase

### ISSUE THREAD

**Issue by dascandy** [dascandy/evoke#1]

**Comment by dascandy** [comment]
- There is a configuration file that's not used
- There's a fair amount of duplication between the different toolsets
- To me the project reading code feels unstructured. Not sure what directly to improve about it though...

**Comment by jonhanks** [comment]
Removing raw owning pointers and cleaning up statically allocated pointers.

This would allow a clean run with address sanitizer enabled.  If you are interested, I can put a pull request together doing that the next time I have time to play with the code.

**Comment by dascandy** [comment]
True.

There's also a lot of duplication between toolsets right now that I think can be removed.

**Comment by dascandy** [comment]
Let's try to have a list of targets that would close this issue. 

- No raw owning pointers
- No memory leaks
- Runs clean with asan, ubsan and tsan.
- No code duplication left between toolsets
- No hardcoded paths to anything that's not portable left
- No hardcoded configuration where not necessary

@jonhanks you're very welcome to do so - it would be half of this list, and probably more than half the work.

**Comment by dascandy** [comment]
Removed all raw owning pointers and all memory leaks. Hardcoded config for predefined components is extracted but still sort of needed.

**Comment by dascandy** [comment]
Tried a run of asan, ubsan and tsan and all three find nothing. That's good news :-)

That should cover the first three bullets fully. Now for the other three...

**Comment by dascandy** [comment]
Duplication removed between toolsets.

**Comment by dascandy** [comment]
Status update:

    No raw owning pointers -> Check.
    No memory leaks -> Check.
    Runs clean with asan, ubsan and tsan. -> Checked with valgrind as a quick check, nothing flagged.
    No code duplication left between toolsets -> Check.
    No hardcoded paths to anything that's not portable left
    No hardcoded configuration where not necessary

**Comment by dascandy** [comment]
Last hardcoded stuff was in Android.
