### ISSUE TITLE
Replace boost::filesystem with std::filesystem

### ISSUE THREAD

**Issue by MrNoyb** [dascandy/evoke#20]
I think it would make sense to use std instead of boost in this case. `std::filesystem` is modeled after `boost::filesystem` and almost the same except for a few wording changes. From what I can see all boost features used in this project have an almost one to one equivalent in the standard library.
This would remove the boost dependency alltogether, which I believe is great, as it means that Evoke doesn't have any external dependencies.

**Comment by dascandy** [comment]
Thank you for this issue! Yes, I agree that it would make the first build of Evoke for a new user much better. It would also fix my Macbook issue - I can't figure out how to set up libraries properly there...

Let me see what I can do.

**Comment by MoAlyousef** [comment]
Hello dascandy
I forked your project and tried to remove the dependency on boost filesystem, the problem is that boost process won’t handle std filesystem. Are you willing to remove boost altogether and use system calls instead?
I could give it a try.

**Comment by dascandy** [comment]
@MoAlyousef doesn't your last pull request fix this too?

**Comment by MoAlyousef** [comment]
> @MoAlyousef doesn't your last pull request fix this too?

It does.

**Comment by dascandy** [comment]
Thank you, @MoAlyousef for fixing this too!
