### ISSUE TITLE
Begin releasing semantically versioned git tags

### ISSUE THREAD

**Issue by mcandre** [dascandy/evoke#25]
Awesome tool! Could we get some git tags to communicate few features, fixes, and any breaking changes?

**Comment by dascandy** [comment]
Sounds good, but at the moment there's a lot of small fixes happening so maybe after this bit. I can retroactively tag the version that was demoed at cppcon, but I don't think it should at any point be used over the current head version.

I'll tag the current version at least as a v0.1, so we have a baseline.

**Comment by dascandy** [comment]
Added v0.2 as first version that builds on MacOS, Linux and Windows. Will add a small readme entry showing the goals for the next few tags.
