### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by dascandy** [dascandy/evoke#27]
**Is your feature request related to a problem? Please describe.**
It is not possible to build, let alone use, Evoke on Windows.

**Describe the solution you'd like**
Make Evoke build and work on Windows with its native compiler, Visual Studio.

**Describe alternatives you've considered**
I've considered convincing the whole planet to use Linux instead, but this has failed.

**Additional context**

**Comment by dascandy** [comment]
Committed boost::process based executor that should support Windows.

**Comment by dascandy** [comment]
Thanks to @MoAlyousef 's work it now builds. I've added an Appveyor build that also runs, checking that it builds on Windows.

Many small things still remain to have full Windows support but as far as this issue is concerned it now at least builds on Windows.

I'll close the issue when it has a way to use the compiler too.

**Comment by MoAlyousef** [comment]
Hello!
I'm trying to get the MSVC compiler to work with evoke. I've implemented the windows toolset, but for some reason, the project::reload function invalidates the components. Could be because of windows path issues.

**Comment by dascandy** [comment]
Hey - can you commit what you have to a branch? I'll see if I can check what's causing this; I've set up a Windows VM with MSVC2017 for this reason.

**Comment by dascandy** [comment]
I debugged what you had on your branch and found a major issue in Project.cpp. I've just pushed the fix for it - one line that was in the Unix ifdef, to add the file to the project, which you also need on Windows. It now crashes inside Windows.cpp generating commands.
