### ISSUE TITLE
How do you envision evoke to be used by large projects like OpenCV?

### ISSUE THREAD

**Issue by graph** [dascandy/evoke#32]
Imagine evoke is complete. How would you envision large projects like OpenCV to migrate to evoke? Or perhaps evoke to automagically support various build systems so OpenCV will not require to do anything? maybe skia is a better example as it's not installed by default. I understand if your ideas are incomplete. I want to know more on your vision.

**Comment by JulienGrv** [comment]
Will the user be able to define the code base structure if they don't agree with the default one?
