### ISSUE TITLE
Evoke goes into data folder

### ISSUE THREAD

**Issue by nathanPro** [dascandy/evoke#43]
**Evoke looks inside data folder**

When I have a data folder in the same directory as my components, evoke goes
inside it an tries to compile what is in it.

**To Reproduce**

I had trouble finding out exactly what triggers the behavior. If I simply have a .cpp file in the data
folder, evoke does recognize it as out of any component. However, when I have the source code
of gcc in the data folder, it goes into it and eventually crashes.

I thought it was a bad idea to upload a zip file with gcc inside it, since it would be huge, so
I am sending a test case with a bash scripts that downloads the version of gcc I downloaded
and extracts it in the correct place.

[crash_case.zip](https://github.com/dascandy/evoke/files/2974180/crash_case.zip)

To run it:

`unzip crash_case.zip`
`cd crash_case`
`./download_gcc.sh`
`evoke`

**Expected behavior**

It reads all the files inside gcc, does not notice that it is not inside a component, and segfaults.

**System**
 - OS: ArchLinux
 - Compiler GCC
 - Version 8.2.1
 - Usage/IDE terminal
 - The evoke version I have is
 acbbcb5c9561d72970c8df0922c5eb91c86ba09e

**Comment by dascandy** [comment]
I'm assuming your expected case is that it does not segfault :-)

I'll look into why it segfaults. It should not do that, no matter what code you give it.

For your current situation, as the data folder is not relevant to the build & may be harmful, it might be best to mark it as not part of your build tree in your "evoke.conf":

blocklist=data

This blocks it from going into the data folder, both not reading the code and not recursing into it, which also makes it faster to use. It also avoids the crash you found.

**Comment by nathanPro** [comment]
Lol, I just realized I wrote that part in the "Expected behavior".

I actually think the expected behavior should be not reading the files inside the data folder. So the fix you proposed is precisely what I am looking for.

Thank you!

**Comment by dascandy** [comment]
Underlying crash was indeed resolving a non-found import to a null pointer, and then using it. Fixed in last commit. 

Thanks for the clear bug report and the help!
