### ISSUE TITLE
Build with gcc8 fails

### ISSUE THREAD

**Issue by xkbeyer** [dascandy/evoke#68]
**Describe the bug**
Building the project with gcc8 fails with:
`evoke/fw/src/dotted.cpp:14:20: error: 'const class std::filesystem::__cxx11::path' has no member named 'filename_is_dot'; did you mean 'filename'?
     if (p.begin()->filename_is_dot())`

**System :**
 - OS: ArchLinux
 - Compiler GCC
 - Version 8.3
 - CMake 3.14

**Additional context**
The std::filesystem does not have such a function. Since boost.filesystem and the std are not fully compatible. An example is this function.
Others can be found [here](https://stackoverflow.com/questions/40899267/how-similar-are-boost-filesystem-and-the-standard-c-filesystem-libraries.)

I would suggest to stick with one and not to support both. Which one depends on which compilers should be supported.

**Comment by Simerax** [comment]
Agree, just tried building the project and ran into the same problem.
@dascandy What do you think about this issue?

**Comment by dascandy** [comment]
Caused by problematic std::filesystem half integration and insufficient CI. Removed std::filesystem, using boost::filesystem everywhere, added more CI checks. Looking into making binary distribution possible at least for Mac, Windows and Ubuntu. 

Can you check if this works properly now?

**Comment by Simerax** [comment]
I was able to build it now. 👍

**Comment by xkbeyer** [comment]
I can build it on Linux and Windows. Thanks.
