### ISSUE TITLE
Add compilation database support

### ISSUE THREAD

**Issue by rLinks234** [dascandy/evoke#8]
As documented here: https://clang.llvm.org/docs/JSONCompilationDatabase.html

This is a useful format which is produced by systems such as [CMake](https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) and consumed by environments such as [CLion](https://www.jetbrains.com/help/clion/compilation-database.html) (this can help resolve issue #5 ).

**Comment by dascandy** [comment]
Picking this up now; should be in before Monday. @rLinks234 can you help me test it? I haven't used it myself before.

**Comment by rLinks234** [comment]
Sure @dascandy  - just ping me here/on slack when you have the code in.

**Comment by dascandy** [comment]
@rLinks234 It's in now; please test whenever you have time. I've looked at the database locally and it looks OK to my interpretation of the spec... but that doesn't guarantee anything, of course :-)

**Comment by dascandy** [comment]
I've tried it myself and CLion imports it fine, but then refuses to use it for anything. Might be related to this so keeping the issue open.

**Comment by dascandy** [comment]
Looks like the compilation database part works well; I can recompile individual files. Reworking the command-line option as it has a fixed name so needs no argument.
