### ISSUE TITLE
evoke generates malformed compiler include argument

### ISSUE THREAD

**Issue by tobiasherzke** [dascandy/evoke#83]
On ubuntu 20.04, `evoke` creates a compiler argument `-I./clude` when it should generate `-Iinclude` or `-I./include`.

Here is a minimized example that demonstrates the error:
```
mkdir -p project/include project/src
cd project
echo '#include "project.hh"' >src/project.cpp
echo 'main(){}' >include/project.hh
evoke | cat
```
(Please ignore the source files' contents apart from the `#include` - this is just a minimized example. `evoke` behaves the same for real code.) `evoke | cat` is done so that evoke does not use terminal magic for its output. The output produced by evoke is:
```
g++ -fdiagnostics-color=always -c -o build/linux/obj/src/project.cpp.o src/project.cpp -I./clude
Error while running g++ -fdiagnostics-color=always -c -o build/linux/obj/src/project.cpp.o src/project.cpp -I./clude
src/project.cpp:1:10: fatal error: project.hh: No such file or directory
    1 | #include "project.hh"
      |          ^~~~~~~~~~~~
compilation terminated.
```
Note the `-I./clude` compiler parameter. As a workaround, I can create a symlink `ln -s include/ clude`, then compilation succeeds.

**Comment by dascandy** [comment]
Can you check if this is fixed on the buildStatus branch? That's where I'm currently developing and I recall fixing this; it's not on master because it accidentally sometimes produces a few multi-gigabyte files still

**Comment by tobiasherzke** [comment]
Yes, it is fixed on that branch. Tank you!

**Comment by dascandy** [comment]
Mind the .evoke.db file; I still need to look into why it sometimes grows huge.

**Comment by dascandy** [comment]
Filed that one as  #84
